### ISSUE TITLE
could not compile `read-fonts-wasm` due to previous error

### ISSUE THREAD

**Issue by moontypespace** [rsheeter/read-fonts-wasm#7]
Hi @rsheeter ,

thanks a lot for the repository. Sadly I am not able to compile it. any idea, what the issue about?

<img width="1445" alt="Screenshot 2023-09-24 at 11 48 52" src="https://github.com/rsheeter/read-fonts-wasm/assets/21055547/4705678e-dfff-4537-8209-ebb9da09f561">

I am a total newbie to Rust, so I am sorry if this a silly question.

Thanks a lot in advance.
Olli

**Comment by rsheeter** [comment]
Oops, didn't notice it had bitrotted. Fixed by 4b7bd0f019da44fc2360e81264d2f346e1fb0319.
